vim.lsp.enable("rust_analyzer")
vim.lsp.enable("lua_ls")
vim.lsp.enable("clangd")
vim.lsp.enable("intelephense")
vim.lsp.enable("gleam")
vim.lsp.enable("gopls")
vim.lsp.enable("basedpyright")
vim.lsp.enable("nil_ls")
